version: "3.7"
services:
  lambda:
    image: lambda:latest
    container_name: lambda
    build:
      dockerfile: Dockerfile
      context: ./
    env_file:
      - ./.env
    environment:
      APP_NAME: ${APP_NAME}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
