version: 2.1

jobs:
  Infrastructure:
    docker:
      - image: cimg/node:15.8.0

    steps:
      - checkout

      - restore_cache:
          keys:
            - cdk-modules-{{ checksum "src/cdk/package.json" }}-1

      - run:
          name: Install
          command: |
            npm install --prefix ./src/cdk

      - run:
          name: Build
          command: |
            npm run build --prefix ./src/cdk

      - run:
          name: Test
          command: |
            npm run test --prefix ./src/cdk

      - save_cache:
          key: cdk-modules-{{ checksum "src/cdk/package.json" }}-1
          paths:
            - src/cdk/node_modules

workflows:
  pipeline:
    jobs:
      - Infrastructure:
